language: java
sudo: false
install: true

env:
  matrix:
    - TARGET=CI
    - TARGET=IT GRADLE_VERSION=1.12
    - TARGET=IT GRADLE_VERSION=2.0
    - TARGET=IT GRADLE_VERSION=2.8

script:
  - ./travis.sh

jdk:
  - oraclejdk8

before_cache:
  - rm -rf $HOME/.m2/repository/org/sonarqube/gradle/gradle-sonarqube-plugin
  - find $HOME/.gradle -type f -name *.lock -exec rm {} +

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
    - '.gradle'
    - '$HOME/.sonar'

notifications:
  email: false
