language: java
sudo: false
install: true

env:
  - GRADLE_VERSION=1.12
  - GRADLE_VERSION=2.0
  - GRADLE_VERSION=2.1
  - GRADLE_VERSION=2.2.1
  - GRADLE_VERSION=2.3
  - GRADLE_VERSION=2.4
  - GRADLE_VERSION=2.5

script:
  - ./gradlew clean build install
  - cd integrationTests
  - mvn clean verify -Dgradle.version=$GRADLE_VERSION

jdk:
  - oraclejdk8

before_cache:
  - rm -rf $HOME/.m2/repository/org/sonarqube/gradle/gradle-sonarqube-plugin
  - find $HOME/.gradle -type f -name *.lock -exec rm {} +

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
    - '.gradle'

notifications:
  email: false
