language: java
sudo: false
install: true

env:
  matrix:
    - RUN_ITS=false
    - RUN_ITS=true GRADLE_VERSION=1.12
    - RUN_ITS=true GRADLE_VERSION=2.0
    - RUN_ITS=true GRADLE_VERSION=2.7
    - RUN_ITS=false PR_ANALYSIS=true

script:
  - ./travis.sh

jdk:
  - oraclejdk8

before_cache:
  - rm -rf $HOME/.m2/repository/org/sonarqube/gradle/gradle-sonarqube-plugin
  - find $HOME/.gradle -type f -name *.lock -exec rm {} +

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
    - '.gradle'

notifications:
  email: false
