language: java
sudo: false
install: true

env:
  - GRADLE_VERSION=2.3
  - GRADLE_VERSION=2.4

script:
  - ./gradlew install
  - cd integrationTests
  - mvn clean verify -Dgradle.version=$GRADLE_VERSION

jdk:
  - oraclejdk8

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
    - '.gradle'

notifications:
  email: false
